<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">18.0</VisualStudioVersion>
    <TargetFrameworks Condition="'$(VisualStudioVersion)' &gt;= '18.0'">net10.0;net9.0;net8.0;net472</TargetFrameworks>
    <TargetFrameworks Condition="'$(VisualStudioVersion)' &lt; '18.0'">net9.0;net8.0;net472</TargetFrameworks>
    <Platforms>AnyCPU;x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Dapplo.Microsoft.Extensions.Hosting.Plugins\Dapplo.Microsoft.Extensions.Hosting.Plugins.csproj" />
    <ProjectReference Include="..\Dapplo.Hosting.Sample.FrameworkLib\Dapplo.Hosting.Sample.FrameworkLib.csproj" />
  </ItemGroup>
</Project>
